name: Build & Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: brew install cmake
    
    - name: Cache llama.cpp
      uses: actions/cache@v3
      with:
        path: llama.cpp
        key: llama-cpp-${{ hashFiles('patch/fixed_kv_patch.diff') }}
    
    - name: Clone llama.cpp
      run: |
        git clone https://github.com/ggerganov/llama.cpp || echo "llama.cpp already exists"
    
    - name: Apply patch
      run: |
        cd llama.cpp
        git apply ../patch/fixed_kv_patch.diff || echo "Could not apply patch, checking file exists"
        cat ../patch/fixed_kv_patch.diff
        ls -la common/common.cpp common/common.h
    
    - name: Build llama.cpp
      run: |
        cd llama.cpp
        mkdir -p build
        cd build
        cmake .. -DLLAMA_METAL=OFF -DLLAMA_AVX=ON -DLLAMA_AVX2=ON
        cmake --build . --config Release -j
    
    - name: Verify build
      run: |
        cd llama.cpp/build
        ls -la bin
        if [ -f "bin/llama-cli" ]; then
          echo "✅ llama-cli built successfully"
          ./bin/llama-cli -h
        else
          echo "❌ Failed to build llama-cli"
          exit 1
        fi
    
    - name: Python syntax check
      run: |
        python -m py_compile scripts/benchmark_kvsplit.py
        python -m py_compile scripts/quick_compare.py
        python -m py_compile scripts/visualize_results.py
        echo "✅ Python scripts pass syntax check"
    
    - name: Shell script check
      run: |
        bash -n scripts/install_kvsplit.sh
        bash -n scripts/capture_memory.sh
        echo "✅ Shell scripts pass syntax check"
